"""
Transport security checks: TLS-01.

TLS-01  Plaintext HTTP endpoints in spec and config files.
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Optional

from ..contract import CheckContext, CheckGroupResult
from ..models import InfraFinding, Severity
from ..constants import MIT_RISK_MAP, CODE_SKIP_DIRS
from ..ignore import load_ignore_patterns, is_ignored

# Output files generated by blastcontain-verify itself — skip to avoid self-referential hits
_SKIP_FILENAMES: frozenset[str] = frozenset({"audit.json"})

_HTTP_PATTERN = re.compile(r'\bhttp://([^\s\'"<>{}|\\^`\[\]]+)', re.IGNORECASE)

# Allow localhost/127.0.0.1 — plaintext is acceptable for loopback
_LOCALHOST_RE = re.compile(r'^localhost|^127\.|^0\.0\.0\.0', re.IGNORECASE)

_SCAN_EXTENSIONS = frozenset({
    ".yaml", ".yml", ".json", ".toml", ".env", ".conf", ".config",
    ".ini", ".xml", ".tf", ".py", ".js", ".ts",
})


def _finding(check_id: str, finding_type: str, severity: Severity,
             title: str, detail: str, remediation: str,
             references: Optional[list[str]] = None,
             evidence: Optional[str] = None) -> InfraFinding:
    mit = MIT_RISK_MAP.get(finding_type, (None, None, None))
    return InfraFinding(
        check_id=check_id, finding_type=finding_type, severity=severity,
        title=title, detail=detail, remediation=remediation,
        references=references or [], evidence=evidence,
        mit_domain=mit[0], mit_causal_id=mit[1], mit_causal_label=mit[2],
    )


def check_tls01_plaintext_endpoints(search_path: str) -> tuple[list[InfraFinding], str]:
    """TLS-01: Plaintext HTTP endpoints in configuration."""
    hits: list[str] = []
    ignore_patterns = load_ignore_patterns(search_path)

    for root, dirs, files in os.walk(search_path, followlinks=False):
        dirs[:] = [d for d in dirs if d not in CODE_SKIP_DIRS and not d.startswith(".")]
        for filename in files:
            if Path(filename).suffix.lower() not in _SCAN_EXTENSIONS:
                continue
            if filename.lower() in _SKIP_FILENAMES:
                continue
            filepath = os.path.join(root, filename)
            rel = os.path.relpath(filepath, search_path)
            if is_ignored(rel, ignore_patterns):
                continue
            try:
                content = Path(filepath).read_text(errors="replace")
            except Exception:
                continue

            for match in _HTTP_PATTERN.finditer(content):
                host = match.group(1).split("/")[0].split(":")[0]
                if not _LOCALHOST_RE.match(host):
                    entry = f"{rel}: http://{match.group(1)[:60]}"
                    if entry not in hits:
                        hits.append(entry)
                    if len(hits) >= 15:
                        break
            if len(hits) >= 15:
                break

    if not hits:
        return [], "PASS"

    return [_finding(
        check_id="TLS-01",
        finding_type="blastcontain.tls.plaintext_endpoint",
        severity=Severity.HIGH,
        title="Plaintext HTTP Endpoints Detected",
        detail=(
            f"Found {len(hits)} non-localhost `http://` URL(s) in configuration and "
            "source files. Inter-agent communication over plaintext HTTP is vulnerable "
            "to man-in-the-middle attacks, credential theft, and request injection."
        ),
        remediation=(
            "Replace all `http://` with `https://` for inter-service communication.\n"
            "For local development TLS: use `mkcert` to generate trusted local certificates.\n"
            "Enforce HTTPS at the API gateway level — never terminate TLS at the agent."
        ),
        references=[
            "https://mkcert.dev/",
        ],
        evidence="; ".join(hits[:5]),
    )], "FAIL"


def run(ctx: CheckContext) -> CheckGroupResult:
    search_path = ctx.cfg.search_path
    findings: list[InfraFinding] = []
    passed: list[str] = []
    skipped: list[dict] = []

    result_findings, status = check_tls01_plaintext_endpoints(search_path)
    if status == "PASS":
        passed.append("TLS-01")
    else:
        findings.extend(result_findings)

    return CheckGroupResult(findings=findings, passed=passed, skipped=skipped)
