ARG BASE_IMAGE=python:3.12-slim
FROM ${BASE_IMAGE}
WORKDIR /opt/plugin
COPY drill/blastcontain_drill/__init__.py blastcontain_drill/__init__.py
COPY drill/blastcontain_drill/contracts/ blastcontain_drill/contracts/
COPY drill/blastcontain_drill/plugins/ blastcontain_drill/plugins/
COPY drill/plugins/reference/worker.py worker.py
COPY drill/LICENSE drill/NOTICE ./
ENTRYPOINT ["/usr/local/bin/python", "-u", "/opt/plugin/worker.py"]
