/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + version */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or update a draft Charter
         * @description Upserts the single mutable draft for `(agent_id, environment)`. The body is the flat packet shape (control + intent fields). Compile conflicts are returned as a preview; only signing is blocked by them.
         */
        post: operations["createCharterDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/derive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Derive-then-ratify — auto-draft a tight Charter from observed reality
         * @description Drafts a Charter from a Verify audit packet and (optionally) a Discovery `observed` capability mapping. Constraints start tight; the allowlist is seeded from observation; objectives come pre-selected by `base_strictness`. The human's job is review + sign, not data entry.
         */
        post: operations["deriveCharterDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign + register the draft: draft → Active
         * @description Compiles the draft (Standards inheritance + Exceptions applied), blocks on blocking conflicts, signs the packet (with the compiled policy embedded), stores it as a new immutable version, and deletes the draft. The commitment gate.
         */
        post: operations["signCharter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the signed Charter bundle (the Guard contract) */
        get: operations["getCharter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history */
        get: operations["listCharterVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The compiled governance.toolkit/v1 policy */
        get: operations["getCompiledPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff two versions — surfaces capability creep */
        get: operations["diffCharterVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote across environments (a governance gate, not a pipeline step)
         * @description Blocked while the source environment's latest scan has CRITICAL findings without remediation proofs. On success a **draft** is created in the target environment — signing it there is the separate sign-off.
         */
        post: operations["promoteCharter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert to the last-known-good signed version */
        post: operations["rollbackCharter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/recertify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quarantine → Active, via a proof addressing the trigger
         * @description The proof's `finding_type` must match the FindingType that triggered quarantine. Produces a new signed version (patch bump) with the proof embedded — the Proof of Remediation.
         */
        post: operations["recertifyCharter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/charters/{agent_id}/exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * File a break-glass Exception (expires; separation of duties)
         * @description Lifts a mandatory objective at the next compile until `expires_at`. The Charter owner cannot approve their own Exception (403).
         */
        post: operations["fileException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List org Standards */
        get: operations["listStandards"];
        put?: never;
        /**
         * Create or update an org Standard
         * @description Every Charter inherits Standard objectives. `mandatory` objectives hard-deny and cannot be loosened by owners; `recommended`/`optional` may be overridden.
         */
        post: operations["upsertStandard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause (graceful suspend) — deny-all / drain / halt */
        post: operations["pauseAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a paused agent
         * @description Quarantined agents cannot resume — only recertify (409).
         */
        post: operations["resumeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emergency stop / kill (break-glass)
         * @description Immediate hard stop; lands in `paused` pending review.
         */
        post: operations["emergencyStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/decommission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decommission (retire) an agent — emits the final Audit Packet
         * @description Tombstone monitoring stays live: decision traffic arriving afterwards raises a HIGH finding and fails the next audit grade.
         */
        post: operations["decommissionAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer ownership (Technical Owner) */
        post: operations["transferOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The decision-rights log (date · change · rationale · approver) */
        get: operations["listOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query stored finding packets */
        get: operations["listFindings"];
        put?: never;
        /**
         * Ingest a scan packet (Verify / Drill / Discovery)
         * @description Accepts a bare packet or a signed `{packet, signature}` bundle (the signature is verified). Evidence is scrubbed (PII/secrets hashed) before persist. A CRITICAL finding against an active prod Charter auto-quarantines the agent.
         */
        post: operations["ingestFindings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query stored decision events (newest first) */
        get: operations["listDecisions"];
        put?: never;
        /**
         * Ingest a Guard/AGT decision CloudEvent
         * @description The Art. 12/14 evidence stream (Guard's LedgerSink posts here). Payloads are scrubbed before persist. Traffic for a decommissioned agent is recorded *and* raises a tombstone finding.
         */
        post: operations["ingestDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/mpl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MPL exposure index — calibrated, oversight-aware, banded */
        get: operations["getMplEstimate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/hitl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** HITL quality — is the human gate real or rubber-stamped? */
        get: operations["getHitlMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/drift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charter drift — declared vs observed */
        get: operations["getDriftReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ledger/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current per-org MPL calibration */
        get: operations["getCalibration"];
        put?: never;
        /** Set per-org MPL calibration */
        post: operations["setCalibration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/audit-packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate (and retain) a signed Audit Packet now
         * @description The regulatory artifact: compliance grade (A–F + rationale), charter history, scan/MPL/HITL/drift summaries, exceptions, operations log. Each call generates and stores a new packet.
         */
        get: operations["generateAuditPacket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/audit-packets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List retained Audit Packets */
        get: operations["listAuditPackets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream (SSE)
         * @description `text/event-stream` of events published after connect. Each SSE message has `event: finding|decision|operation` and a JSON `data:` payload `{seq, type, agent_id, at, data}`. The stream opens with a `: connected` comment line.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All known agents with charter state */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet-wide compliance status */
        get: operations["getFleet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/violations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All CRITICAL/HIGH findings across the fleet */
        get: operations["listViolations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            detail?: string | Record<string, never>;
        };
        /** @enum {string} */
        LifecycleState: "discovered" | "draft" | "active" | "paused" | "quarantined" | "decommissioned" | "archived";
        /**
         * @default interactive
         * @enum {string}
         */
        AutonomyMode: "interactive" | "autonomous";
        /**
         * @default balanced
         * @enum {string}
         */
        BaseStrictness: "locked" | "balanced" | "permissive";
        /** @enum {string} */
        ComplianceGrade: "A" | "B" | "C" | "D" | "F";
        EnvironmentConstraints: {
            /** @default true */
            read_only_rootfs?: boolean;
            /** @default true */
            egress_blocked?: boolean;
            /** @default 1 */
            max_trust_tier?: number;
            /** @default true */
            verify_required?: boolean;
        };
        DelegationRules: {
            /**
             * @description 0 = no delegation.
             * @default 0
             */
            max_chain_depth?: number;
            allowed_tiers?: number[];
            /** @default true */
            require_parent_approval?: boolean;
        };
        HitlConfig: {
            /** @description Legacy gate tokens (e.g. destructive_apis) or tool names. */
            required_for?: string[];
            /** @default 300 */
            timeout_sec?: number;
            escalation_contact?: string | null;
        };
        RemediationProof: {
            /** @example blastcontain.env.model_weights_writable */
            finding_type: string;
            /** @example pr://42 */
            evidence_uri: string;
            verified_by?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
        };
        Objective: {
            /** @description A catalog concern id (e.g. no-pii-egress, approved-tools-only). */
            id: string;
            /**
             * @default self
             * @enum {string}
             */
            enforcement_level?: "mandatory" | "recommended" | "optional" | "self";
            params?: Record<string, never>;
            /** @description Standard id when inherited. */
            inherited_from?: string | null;
            /** @description Rule names this objective compiled to (compiler fills). */
            compiled_refs?: string[];
        };
        /** @description The flat packet shape — control layer + Intent layer + lifecycle envelope. POST bodies omit signing/lifecycle fields; the platform manages those. */
        CharterDocument: {
            agent_id: string;
            environment: string;
            version: string;
            trust_tier: number;
            permitted_tools?: string[];
            permitted_apis?: {
                url?: string;
                methods?: string[];
            }[];
            mcp_servers?: {
                name?: string;
                url?: string;
            }[];
            environment_constraints?: components["schemas"]["EnvironmentConstraints"];
            delegation_rules?: components["schemas"]["DelegationRules"];
            hitl_config?: components["schemas"]["HitlConfig"];
            remediation_proofs?: components["schemas"]["RemediationProof"][];
            transparency_label?: string | null;
            draft?: boolean;
            autonomy_mode?: components["schemas"]["AutonomyMode"];
            base_strictness?: components["schemas"]["BaseStrictness"];
            objectives?: components["schemas"]["Objective"][];
            state?: components["schemas"]["LifecycleState"];
            owner?: string | null;
            derived_from_scan?: string | null;
            /** Format: date-time */
            signed_at?: string | null;
            signed_by?: string | null;
            signing_key_id?: string | null;
        };
        CharterPacket: components["schemas"]["CharterDocument"] & {
            /** @description The platform compiler's authoritative output — inside the signed packet, so tamper-evident end to end. */
            compiled_policy?: components["schemas"]["CompiledPolicy"];
        };
        /** @description blastcontain-core signing block (Ed25519 preferred, HMAC fallback). */
        Signature: {
            /** @enum {string} */
            algorithm?: "ed25519" | "sha256-hmac";
            key_id?: string;
            value?: string;
            /** @enum {string} */
            value_encoding?: "base64" | "hex";
            /** @constant */
            canonical?: "json-sort-keys-tight";
            /** Format: date-time */
            signed_at?: string;
            /** @description ed25519 only — base64 of the 32-byte raw public key. */
            public_key?: string;
            /** @constant */
            public_key_encoding?: "base64-raw";
            /** @description Present (true) only when signed with the shared dev HMAC key — integrity, not attestation. Guard rejects these by default. */
            advisory?: boolean;
        };
        SignedCharterBundle: {
            packet: components["schemas"]["CharterPacket"];
            signature: components["schemas"]["Signature"];
        };
        Rule: {
            /** @example no-prod-data-mutation-destructive */
            name: string;
            /** @example action.type in ['delete', 'drop', 'truncate'] */
            condition: string;
            /** @enum {string} */
            action: "allow" | "deny" | "require_approval";
            approvers?: ("self" | "central")[];
            concern?: string;
        };
        /** @description A governance.toolkit/v1 ruleset (first matching rule wins). */
        CompiledPolicy: {
            /** @constant */
            apiVersion?: "governance.toolkit/v1";
            /** @example invoice-bot-prod */
            name?: string;
            agent_id?: string;
            environment?: string;
            autonomy_mode?: components["schemas"]["AutonomyMode"];
            /** @constant */
            default_action?: "deny";
            rules?: components["schemas"]["Rule"][];
        };
        CompileConflict: {
            objective_id?: string;
            reason?: string;
            /** @description Blocking conflicts stop signing (reconcile or file an Exception). */
            blocking?: boolean;
        };
        CharterDiff: {
            from_version?: string;
            to_version?: string;
            permitted_tools?: components["schemas"]["AddedRemoved"];
            permitted_apis?: components["schemas"]["AddedRemoved"];
            mcp_servers?: components["schemas"]["AddedRemoved"];
            objectives?: components["schemas"]["AddedRemoved"];
            environment_constraints?: {
                [key: string]: {
                    from?: unknown;
                    to?: unknown;
                };
            };
            trust_tier?: {
                from?: number;
                to?: number;
            };
            autonomy_mode?: {
                from?: string;
                to?: string;
            };
            /** @description True when capability grew (tools/APIs/MCP added, objectives removed, tier raised, or a constraint loosened). */
            capability_creep?: boolean;
        };
        AddedRemoved: {
            added?: unknown[];
            removed?: unknown[];
        };
        Operation: {
            /** @enum {string} */
            op?: "register" | "pause" | "resume" | "quarantine" | "recertify" | "kill" | "rollback" | "decommission" | "archive" | "recommission" | "transfer_owner" | "promote" | "exception" | "sign";
            from_state?: components["schemas"]["LifecycleState"];
            to_state?: components["schemas"]["LifecycleState"];
            actor?: string;
            reason?: string;
            params?: Record<string, never>;
            /** Format: date-time */
            at?: string;
        };
        LifecycleResult: {
            agent_id?: string;
            environment?: string;
            state?: components["schemas"]["LifecycleState"];
            operation?: components["schemas"]["Operation"];
        };
        ExceptionRecord: {
            objective_id?: string;
            agent_id?: string;
            environment?: string;
            justification?: string;
            granted_by?: string;
            /** Format: date-time */
            granted_at?: string;
            /** Format: date-time */
            expires_at?: string;
            scope?: string;
        };
        Standard: {
            /** @example org-baseline */
            id: string;
            name?: string;
            version?: string;
            /** @description enforcement_level must be mandatory|recommended|optional. */
            objectives?: components["schemas"]["Objective"][];
            /** Format: date-time */
            updated_at?: string | null;
        };
        Finding: {
            /** @example ENV-02 */
            check_id?: string;
            /** @example blastcontain.env.egress_unrestricted */
            finding_type?: string;
            /** @enum {string} */
            severity?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
            title?: string;
            detail?: string;
            remediation?: string;
            /** @description Scrubbed before persist ([scrubbed:kind:hash] tokens). */
            evidence?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @description A Verify/Drill/Discovery scan packet (shape is tool-defined). */
        FindingPacket: {
            scan_id?: string;
            agent_id?: string;
            environment?: string;
            /** Format: date-time */
            scanned_at?: string;
            /** @example PASSED */
            status?: string;
            summary?: {
                critical?: number;
                high?: number;
                medium?: number;
            };
            findings?: components["schemas"]["Finding"][];
            /** @description Added by the platform when scrubbing replaced spans. */
            evidence_scrubbed?: number;
        } & {
            [key: string]: unknown;
        };
        DecisionData: {
            agent_id?: string;
            environment?: string;
            tool?: string;
            /** @example read */
            action_type?: string;
            /**
             * @description The evaluated outcome.
             * @enum {string}
             */
            decision?: "allow" | "ask" | "deny";
            /**
             * @description The outcome after ask resolution.
             * @enum {string}
             */
            final?: "allow" | "deny";
            rule?: string | null;
            /** @enum {string|null} */
            approver?: "self" | "central" | null;
            approver_id?: string | null;
            /** @enum {string|null} */
            ask_choice?: "allow_once" | "allow_always" | "deny" | null;
            risk_tag?: string | null;
            concern?: string | null;
            reason?: string | null;
            latency_ms?: number;
            degraded?: boolean;
            /** Format: date-time */
            ts?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description CloudEvents 1.0 envelope (Guard's telemetry format). */
        DecisionEvent: {
            /** @constant */
            specversion?: "1.0";
            /** @example com.blastcontain.guard.decision */
            type?: string;
            /** @example blastcontain-guard/invoice-bot */
            source?: string;
            id?: string;
            /** Format: date-time */
            time?: string;
            /** @description The tool name. */
            subject?: string;
            /** @constant */
            datacontenttype?: "application/json";
            data?: components["schemas"]["DecisionData"];
        } & {
            [key: string]: unknown;
        };
        /** @description Per-org MPL overrides — the dollars are yours, not ours. */
        MplCalibration: {
            /** @description Overrides per classification label (PII, PHI, …). */
            base_values?: {
                [key: string]: number;
            };
            regulatory_multipliers?: {
                [key: string]: number;
            };
            /** @default 1 */
            global_scale?: number;
            /** @default USD */
            currency?: string;
            note?: string;
        };
        MplReport: {
            agent_id?: string;
            environment?: string;
            /** @description The calibrated exposure value. */
            exposure?: number;
            currency?: string;
            /** @enum {string} */
            band?: "LOW" | "MODERATE" | "HIGH" | "SEVERE";
            /** @description 0.6 healthy gate · 0.9 rubber-stamped · 1.0 none. */
            oversight_factor?: number;
            calibrated?: boolean;
            methodology?: string;
            /** @description Back-compat alias of exposure. */
            mpl_usd?: number;
            inputs?: {
                classification?: string;
                volume?: number;
                regime?: string;
                business_context?: string;
                hops?: number;
                trust_tier?: number;
                max_tier_in_chain?: number;
                /** @enum {string} */
                oversight?: "none" | "gated" | "gated_low_quality";
            };
        };
        HitlMetrics: {
            agent_id?: string;
            environment?: string;
            events_total?: number;
            by_decision?: {
                allow?: number;
                ask?: number;
                deny?: number;
            };
            asks_total?: number;
            approvals?: number;
            overrides?: number;
            approval_rate?: number | null;
            override_rate?: number | null;
            allow_always_count?: number;
            approval_latency_ms?: {
                median?: number | null;
                p95?: number | null;
                samples?: number;
            };
            /** @description ≥20 asks, ≥95% approved, median latency under 2s. */
            rubber_stamp_risk?: boolean;
            /** @description [concern, deny-count] pairs, highest first. */
            top_denied_concerns?: [
                string,
                number
            ][];
            degraded_events?: number;
            notes?: string;
        };
        DriftReport: {
            agent_id?: string;
            environment?: string;
            charter_version?: string;
            decisions_analyzed?: number;
            /** @description Permitted tools with zero runtime use (right-sizing). */
            unused_grants?: string[];
            unlisted_attempts?: {
                tool?: string;
                attempts?: number;
                denied?: number;
            }[];
            /** @description Repeatedly human-approved gated actions → allowlist proposals. */
            learning_candidates?: {
                tool?: string;
                action_type?: string;
                approvals?: number;
                proposal?: string;
            }[];
            scan_contradictions?: {
                constraint?: string;
                declared?: boolean;
                contradicted_by?: string[];
            }[];
            drift_detected?: boolean;
        };
        AuditPacket: {
            /** @constant */
            packet_type?: "blastcontain.audit_packet/v1";
            /** @enum {string} */
            kind?: "periodic" | "final";
            agent_id?: string;
            environment?: string;
            /** Format: date-time */
            generated_at?: string;
            compliance?: {
                grade?: components["schemas"]["ComplianceGrade"];
                rationale?: string[];
            };
            charter?: {
                version?: string;
                state?: components["schemas"]["LifecycleState"];
                trust_tier?: number;
                autonomy_mode?: string;
                signed_at?: string | null;
                signed_by?: string | null;
                objectives?: string[];
                permitted_tools?: string[];
                remediation_proofs?: components["schemas"]["RemediationProof"][];
                owner?: string | null;
            } | null;
            versions?: Record<string, never>[];
            scan?: {
                status?: string;
                scanned_at?: string | null;
                summary?: Record<string, never>;
                open_critical_types?: string[];
            };
            mpl?: components["schemas"]["MplReport"];
            hitl?: components["schemas"]["HitlMetrics"];
            drift?: components["schemas"]["DriftReport"];
            exceptions?: Record<string, never>[];
            operations?: Record<string, never>[];
        };
        AuditPacketBundle: {
            packet: components["schemas"]["AuditPacket"];
            signature: components["schemas"]["Signature"];
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such charter / draft / agent. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The state machine or compile gate refused (e.g. blocking conflicts, invalid lifecycle transition, unaddressed CRITICALs). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example invoice-bot */
        AgentId: string;
        /** @description Deployment environment (half of the charter key). */
        EnvProd: string;
        /** @description Environment filter; empty = all environments. */
        EnvAll: string;
        /** @description Environment filter; empty = all environments. */
        EnvFilter: string;
        Limit: number;
        /** @description Decision-window size for the analysis. */
        Limit1000: number;
    };
    requestBodies: {
        ActorReason: {
            content: {
                "application/json": {
                    /** @description Named accountability. */
                    actor: string;
                    reason?: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status?: "ok";
                        version?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    createCharterDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "agent_id": "invoice-bot",
                 *       "environment": "prod",
                 *       "version": "1.0.0",
                 *       "trust_tier": 1,
                 *       "permitted_tools": [
                 *         "query_invoice",
                 *         "send_receipt"
                 *       ],
                 *       "autonomy_mode": "interactive",
                 *       "base_strictness": "balanced",
                 *       "objectives": [
                 *         {
                 *           "id": "no-prod-data-mutation"
                 *         },
                 *         {
                 *           "id": "no-pii-egress"
                 *         }
                 *       ],
                 *       "environment_constraints": {
                 *         "read_only_rootfs": true,
                 *         "egress_blocked": false,
                 *         "max_trust_tier": 1,
                 *         "verify_required": true
                 *       },
                 *       "owner": "alice@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["CharterDocument"];
            };
        };
        responses: {
            /** @description Draft stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        /** @example invoice-bot:prod */
                        charter_id?: string;
                        /** @constant */
                        state?: "draft";
                        draft_row?: number;
                        conflicts?: components["schemas"]["CompileConflict"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deriveCharterDraft: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description A Verify audit packet (`packet` payload). */
                    audit_packet?: Record<string, never>;
                    observed?: {
                        tools?: string[];
                        apis?: Record<string, never>[];
                        mcp_servers?: Record<string, never>[];
                        trust_tier?: number;
                    };
                    autonomy_mode?: components["schemas"]["AutonomyMode"];
                    base_strictness?: components["schemas"]["BaseStrictness"];
                    owner?: string;
                };
            };
        };
        responses: {
            /** @description Derived draft stored and returned. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        charter_id?: string;
                        /** @constant */
                        state?: "draft";
                        document?: components["schemas"]["CharterDocument"];
                        conflicts?: components["schemas"]["CompileConflict"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    signCharter: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Who signs (named accountability). */
                    actor: string;
                    /** @description Optional version override. */
                    version?: string;
                };
            };
        };
        responses: {
            /** @description Signed and active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        signed?: boolean;
                        /** @constant */
                        state?: "active";
                        version?: string;
                        /** @description True when the platform signed with the shared dev HMAC key (integrity only — Guard rejects these by default). */
                        advisory_signature?: boolean;
                        conflicts?: components["schemas"]["CompileConflict"][];
                        bundle?: components["schemas"]["SignedCharterBundle"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCharter: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
                /** @description Return the unsigned draft instead, when one exists. */
                include_draft?: boolean;
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed bundle (or, with `include_draft=true`, the draft document). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedCharterBundle"] | {
                        /** @constant */
                        draft?: true;
                        document?: components["schemas"]["CharterDocument"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCharterVersions: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All signed versions, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent_id?: string;
                        environment?: string;
                        versions?: {
                            version?: string;
                            state?: components["schemas"]["LifecycleState"];
                            superseded?: boolean;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCompiledPolicy: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
                fmt?: "json" | "yaml";
                /** @description Compile the current draft live instead of the signed policy. */
                draft?: boolean;
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ruleset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompiledPolicy"];
                    "application/yaml": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    diffCharterVersions: {
        parameters: {
            query: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
                from_version: string;
                to_version: string;
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Structured capability diff. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterDiff"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    promoteCharter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example staging */
                    from_env: string;
                    /** @example prod */
                    to_env: string;
                    actor: string;
                };
            };
        };
        responses: {
            /** @description Draft created in the target environment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        promoted?: boolean;
                        draft_environment?: string;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    rollbackCharter: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor: string;
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Prior version re-issued (new signature, active). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rolled_back?: boolean;
                        version?: string;
                        /** @constant */
                        state?: "active";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    recertifyCharter: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor: string;
                    proof: components["schemas"]["RemediationProof"];
                };
            };
        };
        responses: {
            /** @description Recertified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        recertified?: boolean;
                        version?: string;
                        /** @constant */
                        state?: "active";
                        proof_of_remediation?: components["schemas"]["RemediationProof"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    fileException: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example block-exfiltration */
                    objective_id: string;
                    justification: string;
                    granted_by: string;
                    /** Format: date-time */
                    expires_at: string;
                    scope?: string;
                };
            };
        };
        responses: {
            /** @description Exception recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        exception?: components["schemas"]["ExceptionRecord"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Separation of duties — owner self-approval refused. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listStandards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All Standards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        standards?: components["schemas"]["Standard"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    upsertStandard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Standard"];
            };
        };
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        standard_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    pauseAgent: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor: string;
                    reason?: string;
                    /**
                     * @default deny-all
                     * @enum {string}
                     */
                    mode?: "deny-all" | "drain" | "halt";
                };
            };
        };
        responses: {
            /** @description Paused; the served packet is re-stamped to `paused`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"] & {
                        /** @description What this pause mode means for in-flight work. */
                        impact?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeAgent: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ActorReason"];
        responses: {
            /** @description Active again. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    emergencyStop: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ActorReason"];
        responses: {
            /** @description Stopped (paused, `break_glass` recorded). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    decommissionAgent: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ActorReason"];
        responses: {
            /** @description Decommissioned; final Audit Packet generated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"] & {
                        final_audit_packet?: {
                            id?: number;
                            grade?: components["schemas"]["ComplianceGrade"];
                            /** Format: date-time */
                            generated_at?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    transferOwner: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    actor: string;
                    /** @description The new Technical Owner. */
                    owner: string;
                };
            };
        };
        responses: {
            /** @description Owner transferred; served packet re-stamped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LifecycleResult"] & {
                        owner?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOperations: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvAll"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only governance actions, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent_id?: string;
                        operations?: components["schemas"]["Operation"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listFindings: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvAll"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored (scrubbed) packets, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent_id?: string;
                        findings?: components["schemas"]["FindingPacket"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestFindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingPacket"] | {
                    packet: components["schemas"]["FindingPacket"];
                    signature: components["schemas"]["Signature"];
                };
            };
        };
        responses: {
            /** @description Ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        finding_count?: number;
                        /** @description null when the packet arrived unsigned. */
                        signature_verified?: boolean | null;
                        /** @description How many PII/secret spans were hashed. */
                        evidence_scrubbed?: number;
                        /** @description True when this packet auto-quarantined the agent. */
                        quarantined?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvAll"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored (scrubbed) CloudEvents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent_id?: string;
                        decisions?: components["schemas"]["DecisionEvent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionEvent"];
            };
        };
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        /** @description Present (true) when the agent is retired. */
                        tombstone_alert?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMplEstimate: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
                classification?: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED" | "PII" | "PHI";
                /** @description Records at risk (scales sublinearly). */
                volume?: number;
                regime?: "STANDARD" | "EU_AI_ACT_HIGH_RISK" | "CANADA_AIDA";
                business_context?: "STANDARD" | "ELEVATED" | "CRITICAL";
                /** @description Delegation hops (blast radius). */
                hops?: number;
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exposure report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MplReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getHitlMetrics: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvAll"];
                /** @description Decision-window size for the analysis. */
                limit?: components["parameters"]["Limit1000"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated gate quality over the decision window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HitlMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDriftReport: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
                /** @description Decision-window size for the analysis. */
                limit?: components["parameters"]["Limit1000"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drift analysis against the signed Charter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCalibration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored calibration (defaults when unset). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        calibration?: components["schemas"]["MplCalibration"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setCalibration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MplCalibration"];
            };
        };
        responses: {
            /** @description Stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        calibration?: components["schemas"]["MplCalibration"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    generateAuditPacket: {
        parameters: {
            query?: {
                /** @description Deployment environment (half of the charter key). */
                env?: components["parameters"]["EnvProd"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed packet bundle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPacketBundle"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAuditPackets: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvAll"];
            };
            header?: never;
            path: {
                /** @example invoice-bot */
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packet index (oldest first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agent_id?: string;
                        audit_packets?: {
                            id?: number;
                            environment?: string;
                            /** @enum {string} */
                            kind?: "periodic" | "final";
                            grade?: components["schemas"]["ComplianceGrade"];
                            /** Format: date-time */
                            generated_at?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                /** @description Environment filter; empty = all environments. */
                env?: components["parameters"]["EnvFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents across charters and drafts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents?: {
                            agent_id?: string;
                            environment?: string;
                            state?: components["schemas"]["LifecycleState"];
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFleet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One row per agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents?: {
                            agent_id?: string;
                            /** @description Latest scan status (UNKNOWN when unscanned). */
                            status?: string;
                            /** Format: date-time */
                            last_scan?: string | null;
                            critical?: number;
                            /** @description environment → lifecycle state */
                            charters?: {
                                [key: string]: components["schemas"]["LifecycleState"];
                            };
                        }[];
                        total?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listViolations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flattened findings with their agent ids. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        violations?: ({
                            agent_id?: string;
                        } & components["schemas"]["Finding"])[];
                        total?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
