"""
The scout pipeline: fetch → dedupe → classify → build a draft-PR plan.

Orchestrates the modules into one run. Pure assembly + a single side-effecting
step (repo.publish) that is gated behind --apply/--open-pr at the CLI, so a plain
run is a safe dry-run preview.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Optional

from . import arxiv as arxiv_mod
from .analyze import Analysis, classify
from .ledger import Ledger
from .tracker import Tracker
from .llm import make_backend
from .render import render_digest, render_scaffold, scaffold_relpath
from .repo import FileWrite, PublishPlan

_CONTRIB_README = (
    "# Scout proposals (inert drafts — NOT shipped, NOT linted)\n\n"
    "Auto-generated by blastcontain-scout, foldered by `<source>/<YYYY-MM>/`. Each\n"
    "file is an INERT `AttackSource` scaffold (`is_available()` -> False) citing a\n"
    "paper. This tree is **excluded from the built wheel and from ruff** — it is a\n"
    "staging area, not product code.\n\n"
    "Ratify one by: verifying the license permits vendoring, vendoring the data /\n"
    "implementing `dataset()`, flipping `is_available()`, setting `revision`, then\n"
    "moving it into `corpus/` and registering it in `corpus/__init__.py` behind an\n"
    "`enable_*` flag.\n"
)


@dataclass
class ScoutConfig:
    repo_root: str
    base_branch: str = "main"
    max_results: int = 50
    threshold: float = 0.5
    base_url: str = "http://localhost:1234/v1"
    model: Optional[str] = None
    ledger_path: str = "tools/scout/state/seen-arxiv.json"
    contrib_dir: str = "drill/blastcontain_drill/corpus/contrib"
    digest_dir: str = "drill/docs/scout"
    database: Optional[str] = None
    record: bool = False
    source: str = "arxiv"          # contrib bucket: contrib/<source>/<YYYY-MM>/
    categories: tuple = arxiv_mod.DEFAULT_CATEGORIES
    terms: tuple = arxiv_mod.DEFAULT_TERMS


@dataclass
class ScoutResult:
    scanned: int
    new: int
    relevant: int
    analyses: list = field(default_factory=list)
    plan: Optional[PublishPlan] = None
    note: str = ""

    @classmethod
    def from_dict(cls, data):
        data = dict(data)
        data['analyses'] = [Analysis(**{**a, 'paper': arxiv_mod.Paper(**a['paper'])})
                            for a in data['analyses']]
        if data['plan'] is not None:
            data['plan'] = PublishPlan(**{**data['plan'],
                'files': [FileWrite(**f) for f in data['plan']['files']]})
        return cls(**data)


def build_plan(cfg: ScoutConfig, today: str) -> ScoutResult:
    root = cfg.repo_root
    if cfg.database and os.path.exists(cfg.database):
        with Tracker(cfg.database, readonly=True) as tracker:
            pending = tracker.pending_publication(root)
        if pending:
            # Retry the exact draft, including its date and branch, without refetching.
            return ScoutResult.from_dict(pending)
    papers = arxiv_mod.fetch(
        max_results=cfg.max_results, categories=cfg.categories, terms=cfg.terms
    )
    ledger = Ledger.load(os.path.join(root, cfg.ledger_path))
    cached = {}
    if cfg.database and os.path.exists(cfg.database):
        with Tracker(cfg.database, readonly=True) as tracker:
            candidates = [p for p in papers if tracker.needs_proposal(p)]
            cached = {p.arxiv_id: tracker.saved_analysis(p) for p in candidates}
            new_papers = [p for p in candidates if cached[p.arxiv_id] is None]
    else:
        new_papers = ledger.filter_new(papers, today)
        candidates = new_papers

    backend = make_backend(cfg.base_url, cfg.model)
    analyses = [cached.get(p.arxiv_id) or classify(p, cfg.terms, backend, cfg.threshold)
                for p in candidates]
    keepers = [a for a in analyses if a.relevant]
    if cfg.record:
        if not cfg.database:
            raise ValueError("Recording requires a database path")
        with Tracker(cfg.database) as tracker:
            tracker.ingest(papers, analyses)

    if not analyses:
        return ScoutResult(len(papers), 0, 0, analyses, None, "no new papers since last run")

    # ── Build the files the PR will add ──────────────────────────────────────
    files: list[FileWrite] = []

    digest_rel = os.path.join(cfg.digest_dir, f"digest-{today}.md")
    digest_text = render_digest(analyses, today, cfg.source)
    files.append(FileWrite(os.path.join(root, digest_rel), digest_text))

    contrib_readme = os.path.join(root, cfg.contrib_dir, "README.md")
    if not os.path.exists(contrib_readme):
        files.append(FileWrite(contrib_readme, _CONTRIB_README))

    for a in keepers:
        if a.kind in ("dataset", "technique"):
            rel = scaffold_relpath(a, cfg.source)          # e.g. arxiv/2026-06/c_x.py
            path = os.path.join(root, cfg.contrib_dir, *rel.split("/"))
            files.append(FileWrite(path, render_scaffold(a)))

    # Ledger update travels with the PR so dedupe state is shared.
    ledger.mark(papers, today)
    ledger_json = json.dumps({"seen": ledger.seen}, indent=2, sort_keys=True)
    files.append(FileWrite(os.path.join(root, cfg.ledger_path), ledger_json))

    plan = PublishPlan(
        branch=f"scout/arxiv-{today}",
        base=cfg.base_branch,
        commit_message=f"scout: {len(keepers)} pending jailbreak paper(s) — {today}",
        pr_title=f"Corpus scout: {len(keepers)} pending jailbreak paper(s) ({today})",
        pr_body=digest_text,
        files=files,
    )
    return ScoutResult(len(papers), len(new_papers), len(keepers), analyses, plan,
                       f"{len(keepers)} relevant proposals; {len(new_papers)} newly classified")
